baseurl                  = "https://crays.ee/"               # Your domain name. Must end with "/"
languageCode             = "en-us"
title                    = "Craysee Webhosting"
theme                    = "base16"
pygmentsStyle            = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
pygmentsuseclasses       = true
googleAnalytics          = "UA-46154855-2"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "02/01/2006"
    dateformfull         = "02/01/2006 15:04"
    favicon              = "/favicon.ico"
    homepage             = "Home"                        # What to call the home page link

# Metadata
    description          = "Our mission is to provide developers with highly performant webhosting in a shared/managed package."            # Max 160 characters show in search results
    twitterCard          = "summary"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage         = "/screenshot.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/pricing/"
    text = "Pricing"
    title = "Pricing"

[[params.mainMenu]]
    link = "/contact/"
    text = "Contact"
    title = "Contact"

[[params.mainMenu]]
    link = "/legal/"
    title = "Legal"
    
    