baseurl                  = "https://crays.ee/"               # Your domain name. Must end with "/"
languageCode             = "en-us"
title                    = "Flor Holvoet - Information Engineer"
theme                    = "sam"
pygmentsStyle            = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
googleAnalytics          = "UA-46154855-2"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "02/01/2006"
    dateformfull         = "02/01/2006 15:04"
    favicon              = "/sam.ico"
    homepage             = "Home"                        # What to call the home page link
    galleryFolder        = "images/"                     # Where you've put your images, after "/content/gallery/" (eg. "images/")
    clickablePhotos      = true                          # Allow links to the full size images
    smallPreviewImages   = true                          # Show thumbnails (small images) instead of using full size images on the gallery page
                                                         # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                      # Folder for image thumbnails (small versions) after "/content/gallery/[galleryFolder]" (eg. "small/")
                                                         # For each image the small version has to have the same filename as the big version.

# Metadata
    description          = "Flor Holvoet is a self-employed Information Engineer & Cloud Solution Architect."            # Max 160 characters show in search results
    twitterCard          = "summary"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage         = "/screenshot.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/about"
    text = "It's me, Flor"
    title = "About"

[[params.mainMenu]]
    link = "/contact"
    text = "Call me crays.ee"
    title = "Contact"

[[params.mainMenu]]
    link = "/legal"
    title = "Legal"
    
